import "server-only";
import { logger } from "@/lib/logging/logger";
import { submitCharterRequest } from "@/features/quote/actions/quote.actions";
import type { CreateQuoteInput } from "@/features/quote/schemas/quote.schema";
import type { MissionType } from "@/database/constants/mission-type";

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * AI-facing shape of a quote request — a flat structure that's easy for
 * a model to fill in from a conversation. Every field is optional here
 * on purpose: the executor no longer gates on "required" fields itself,
 * because `createQuoteSchema` (via submitCharterRequest below) is the
 * single source of truth for what's actually required. Missing or
 * invalid fields come back as structured `fieldErrors` instead.
 *
 * Field names and shape intentionally mirror `CreateQuoteInput`
 * (@/features/quote/schemas/quote.schema) — the same structure the
 * website's charter request form submits — so mapping between the two
 * is a straight pass-through with no invented fields.
 */
export interface AiQuoteRequestInput {
  customerName?: string;
  customerEmail?: string;
  customerPhone?: string;
  customerCompany?: string;
  departureAirportCode?: string;
  destinationAirportCode?: string;
  departureDate?: string;
  returnDate?: string;
  isRoundTrip?: boolean;
  passengerCount?: number;
  missionType?: MissionType;
  /** The Aircraft `_id` of a specific aircraft confirmed via search_aircraft. */
  aircraftPreference?: string;
  budgetRangeMin?: number;
  budgetRangeMax?: number;
  specialRequests?: string;
  hasMedicalEquipment?: boolean;
  medicalEquipmentDetails?: string;
  hasVipRequirements?: boolean;
  vipRequirementsDetails?: string;
  hasCargo?: boolean;
  cargoDetails?: string;
  hasPets?: boolean;
  petsDetails?: string;
  hasDangerousGoods?: boolean;
  dangerousGoodsDetails?: string;
}

export interface AiQuoteRequestResult {
  success: boolean;
  /** The real, sequential quote number generated by the quotation system. */
  quoteNumber?: string;
  message: string;
  /** Present on validation failure — field path → human-readable message. */
  fieldErrors?: Record<string, string>;
}

// ── Service ───────────────────────────────────────────────────────────────────

/**
 * Submits a charter quotation request captured by the AI Concierge
 * through the exact same pipeline the website's charter request form
 * uses: `submitCharterRequest` → `createQuoteSchema` validation →
 * `createQuoteFromInput` (Quote document + admin email notification).
 *
 * This is deliberately a thin mapping layer, not a second quotation
 * system — there is no separate Quote creation, validation, or email
 * logic here. An AI-submitted quote is indistinguishable in the
 * database, the admin dashboard, or the notification emails from one
 * submitted through the public form.
 */
export async function submitQuoteRequestForAI(
  input: AiQuoteRequestInput
): Promise<AiQuoteRequestResult> {
  // Structurally matches CreateQuoteInput; validated for real by
  // createQuoteSchema.safeParse() inside submitCharterRequest regardless
  // of what TypeScript believes about this object going in — the cast
  // below just avoids re-declaring the schema's shape a second time.
  const payload = {
    contactInfo: {
      fullName: input.customerName,
      email: input.customerEmail,
      phone: input.customerPhone,
      company: input.customerCompany,
    },
    passengerCount: input.passengerCount,
    departureAirportCode: input.departureAirportCode,
    destinationAirportCode: input.destinationAirportCode,
    departureDate: input.departureDate,
    returnDate: input.returnDate,
    isRoundTrip: input.isRoundTrip ?? false,
    aircraftPreference: input.aircraftPreference,
    missionType: input.missionType,
    budgetRangeMin: input.budgetRangeMin,
    budgetRangeMax: input.budgetRangeMax,
    specialRequests: input.specialRequests,
    hasMedicalEquipment: input.hasMedicalEquipment ?? false,
    medicalEquipmentDetails: input.medicalEquipmentDetails,
    hasVipRequirements: input.hasVipRequirements ?? false,
    vipRequirementsDetails: input.vipRequirementsDetails,
    hasCargo: input.hasCargo ?? false,
    cargoDetails: input.cargoDetails,
    hasPets: input.hasPets ?? false,
    petsDetails: input.petsDetails,
    hasDangerousGoods: input.hasDangerousGoods ?? false,
    dangerousGoodsDetails: input.dangerousGoodsDetails,
    attachments: [],
  } as unknown as CreateQuoteInput;

  const result = await submitCharterRequest(payload);

  if (!result.success) {
    logger.info("AI Concierge quote request failed validation", {
      customerEmail: input.customerEmail,
      fieldErrors: result.fieldErrors,
      error: result.error,
    });

    return {
      success: false,
      fieldErrors: result.fieldErrors,
      message:
        result.error ??
        "The quotation request could not be submitted — some details need correcting.",
    };
  }

  logger.info("AI Concierge quote request submitted", {
    quoteNumber: result.quoteNumber,
    customerEmail: input.customerEmail,
    route: `${input.departureAirportCode} → ${input.destinationAirportCode}`,
    travelDate: input.departureDate,
    passengerCount: input.passengerCount,
  });

  return {
    success: true,
    quoteNumber: result.quoteNumber,
    message:
      `Quote request received. Your reference number is ${result.quoteNumber}. ` +
      `Our operations team will review it and follow up at ${input.customerEmail} ` +
      `with aircraft recommendations and pricing.`,
  };
}