import { useConcierge } from "../context/ConciergeContext";
import { parseToolResults } from "../lib/toolResults";
import type { ConciergeMessage } from "../types";

const DEFAULT_FOLLOW_UPS = ["Recommend an aircraft", "Get a quotation", "What destinations do you operate?"];

/**
 * Chosen from what the reply actually contained (which tool results, if
 * any, it carries) — not generated by the model itself, so this never
 * risks suggesting something the concierge can't actually help with.
 */
function followUpsFor(message: ConciergeMessage): string[] {
  if (message.toolCalls.length === 0) return DEFAULT_FOLLOW_UPS;

  const kinds = new Set(parseToolResults(message.toolCalls).map((result) => result.kind));

  if (kinds.has("aircraft")) {
    return ["Compare with another aircraft", "Is it pet friendly?", "Get a quotation"];
  }
  if (kinds.has("airport")) {
    return ["Any nearby airports?", "Recommend an aircraft for this route", "Get a quotation"];
  }
  if (kinds.has("company")) {
    return ["Recommend an aircraft", "What destinations do you operate?"];
  }

  return DEFAULT_FOLLOW_UPS;
}

export function FollowUpSuggestions({ message }: { message: ConciergeMessage }) {
  const { sendMessage, isSending } = useConcierge();
  if (isSending) return null;

  return (
    <div className="flex flex-wrap gap-1.5 pl-8">
      {followUpsFor(message).map((suggestion) => (
        <button
          key={suggestion}
          type="button"
          onClick={() => void sendMessage(suggestion)}
          className="rounded-lg border border-slate-200 px-2.5 py-1 font-body text-[11px] text-slate-600 transition-colors duration-300 ease-editorial hover:border-blue-400 hover:text-blue-600"
        >
          {suggestion}
        </button>
      ))}
    </div>
  );
}